import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from '@/components';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
/*
* SEP Friendly => Esto ayuda a los boot de gooogle para buscar algo  en especifico de 
*  esta pagina
* https://developers.google.com/search/docs/crawling-indexing/special-tags?hl=es-419
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


//RootLayout =>Es un Higher Order Components ya que es un component que recibe componet como hijos
export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="es">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
  
}
